# Generated by Django 4.2.7 on 2023-12-06 15:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0002_alter_review_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(1, message='Число для рейтинга не может быть ниже 1.'), django.core.validators.MaxValueValidator(12, message='Число для рейтинга не может быть больше 12.')], verbose_name='Рейтинг'),
        ),
    ]
