# Generated by Django 4.2.7 on 2023-12-18 15:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('abstract', '0004_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='favorite',
            name='product_price',
        ),
        migrations.AddField(
            model_name='favorite',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='abstract.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favorite',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
